= F# vs Scala =

F# klady oproti Scale:

* Type Providers.
  ** Ve Scale jsou nejblíže whitebox makra.
    *** Není však zřejmé, jak pomocí whitebox maker uspokojivě vyřešit situaci,
      kdy aplikace využívá jen zlomek z obrovského množství typů,
      které TP poskytuje. V ideálním případě by měl kompilátor pracovat
      pouze s využívanými typy, nikoliv se všemi poskytovanými typy.
    *** Nevýhodou whitebox maker je, že příliš dobře nefungují v prostředí IntelliJ IDEA
      (pro každé makro je třeba napsat speciální plugin -- viz
      https://blog.jetbrains.com/scala/2015/10/14/intellij-api-to-build-scala-macros-support/[IntelliJ
      API to Build Scala Macros Support])
      a že momentálně nejsou součástí scala.meta.
  ** Potenciální nevýhodou TP je, že mohou generovat typy z dat
    mimo repozitář projektu, což může vést k nereplikovatelným buildům.
* `let` v F# není rekurzivní na rozdíl od `def` nebo `val` ve Scale.
* Active Patterns lze parametrizovat uvnitř `match`.
  ** Na rozdíl od extraktorů ve Scale, kde to nejde --
    parametrizace se musí provést před `match`
    (parametry se předají funkci, jenž na jejich základě vrátí
    extraktor, který je třeba uložit do proměnné).
    V F# existuje stručnější zápis.
* CLR podporuje eliminaci tail callů.
  ** Ve Scale lze implementovat trampolíny. Nevýhodou trampolín je,
    že jejich implementace není úplně jednoduchá a navíc zatěžují GC.
  ** Eliminace tail callů v F# má určitá omezení --
    například pro funkce, jenž vrací `unit`. Podrobnosti viz
    https://blogs.msdn.microsoft.com/fsharpteam/2011/07/08/tail-calls-in-f/[Tail
    calls in F#].
* Lepší typová inference.
  ** Typový systém Scaly je příliš silný, kvůli čemuž je těžké udělat
    typovou inferenci jako pro Damas-Milnerův typový systém.
  ** Navíc i lokální typová inference ve Scale je ad-hoc.
    Např. to, kdy probíhá instanciace typových parametrů --
    podrobnosti viz přednáška https://www.youtube.com/watch?v=YIQjfCKDR5A[Dotty
    and types: the story so far],
    kde Guillaume Martres mj. kritizuje scalac.
  ** Naneštěstí ani Dotty v tomto ohledu nevypadá o mnoho lépe:
    *** Příkladem jsou různé ad-hoc rozhodnutí, kdy se místo nejpřesnějšího
      typu inferuje méně přesný, ale kratší typ.
    *** Další příklad je v https://github.com/lampepfl/dotty/issues/1093[SIP:
      Widening of case class apply to better emulate ADTs].
      Motivací tohoto SIPu bylo pomoci typové inferenci.
* Při programování v F# se používají mutable kolekce
  ze standardní knihovny, zatímco Scala si vytvořila novou
  knihovnu kolekcí (je třeba převádět mezi kolekcemi
  ze Scaly a Javy).
* Lepší enumy.
* Není třeba psát `new`.
* F# má klíčové slovo `use` pro uvolňování zdrojů, když je opuštěn scope proměnné.
  ** Ve Scale je třeba použít try-finally nebo knihovnu scala-arm.
    Obě možnosti jsou však méně přehledné než `use` z F#.
* F# nemá implicitní konverze.
  ** Ve Scale často vedou na elegantní, ale těžko srozumitelný kód.
    *** Např. knihovna http4s umožňuje psát `Ok("Hello!")`,
      ačkoliv `Ok` nejde aplikovat na žádný argument.
      Překlad však uspěje díky implicitní konverzi `OkSyntax(Ok)("Hello!")`.
      Navíc je psaní kódu méně pohodlné, neboť IntelliJ IDEA
      napovídá parametry pro `Ok` (nikoliv pro `OkSyntax(Ok)`),
      jenže `Ok` žádné parametry nemá.
  ** Jedním z důsledků je lepší typová inference.
* Scala má velmi pokročilé vlastnosti, které jen málokdo umí použít.

F# zápory oproti Scale:

* V F# chybí typové třídy (nebo implicitní parametry nebo možnost
  dodatečné implementace rozhraní).
  ** Pozitivní je, že se uvažuje o jejich přidání --
    viz článek http://www.mlworkshop.org/2016-7.pdf[Classes for the Masses].
* F# jsou 2 jazyky v jednom (jeden funkcionální a jeden objektový).
  Scala však skutečně kombinuje funkcionální i objektový přístup
  do jednoho jazyka.
  ** Záznamy a ani discriminated uniony v F# se nechovají jako klasické třídy.
  ** Funkce v F# nepodporují pojmenované a nepovinné parametry,
    metody v F# to umí.
* Type Providers v F# neumí generovat typy na základě jiných typů.
  ** To ve Scale jde pomocí whitebox maker.
* Pravidla pro parsování kódu F# jsou komplikovaná.
  ** Zejména lexikální filtrování obsahuje řadu výjimek.
    Lidem pak např. dělá problémy chápat, proč se změní chování kódu
    když se zvětší odsazení -- viz
    https://github.com/Microsoft/visualfsharp/issues/1019[Different indentation
    level changes behaviour of the code].
* Quotationy v F# nepodporují generika.
  ** Omezení quotationů se přenáší mj. na type providery.
* CLR je stále příliš vázané na jednu firmu (Microsoft).
* Scala má higher-kinded typy.
  ** Pro jejich vyjádření v F# můžeme použít defunkcionalizaci. Příklad z knihovny
    https://github.com/palladin/Higher[Higher]:
+
[source,fsharp]
----
// Represents type application.
// To ensure type-safety we use a secret token based control access policy.
type App<'F, 'T> (token : 'F, value : obj) =
    do
        if Object.ReferenceEquals(token, Unchecked.defaultof<'F>) then
            raise <| InvalidOperationException "Invalid token"

    // Apply the secret token to have access to the encapsulated value.
    member __.Apply(token' : 'F) =
        if Object.ReferenceEquals(token, token')
        then value
        else raise <| InvalidOperationException "Invalid token"

[<AbstractClass>]
type Functor<'F>() =
    abstract Map<'A, 'B> : ('A -> 'B) -> App<'F, 'A> -> App<'F, 'B>

type List private () =
    static let token = List()
    static member Inj (value : 'T list) : App<List, 'T> =
        App<_, _>(token, value)
    static member Prj (app : App<List, 'T>) : 'T list =
        app.Apply(token) :?> _

type ListFunctor() =
    inherit Functor<List>()

    override __.Map f x = x |> List.Prj |> List.map f |> List.Inj
----
Pomocí tokenu je zajištěno, že instance `App<List, 'T>` může vytvářet pouze `List.Inj`
(k vytvoření je třeba token -- tj. hodnota typu `List`, která není `null`)
a rozbalovat je může pouze `List.Prj`.
* Horší build systémy.
* Z funkce definované v těle třídy nebo metody nejde volat
  `private` a `protected` metody.

Nejasné, zda se jedná o klad nebo o zápor F#:

* F# nemá modifikátor přístupu `protected`.
  ** Nebývá potřeba.
* F# nemá makra.
  ** Některé z výhod maker přinášejí type providers.
  ** Stojí zbylé výhody maker za zkomplikování jazyka nebo je lepší
    zjistit, co dalšího makra přinášejí oproti type providers,
    a nejpřínosnější věci implementovat přímo do jazyka?
